=== fktt-module/datasheets/bahnhof.dtd
<!ELEMENT bahnhof (name,kuerzel,typ,verwaltung,maszstab,modulnr,plan?,gleise,pv?,gv?,bemerkung?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT kuerzel (#PCDATA)>
<!ELEMENT typ (#PCDATA)>
<!ELEMENT verwaltung (#PCDATA)>
<!ELEMENT maszstab (#PCDATA)>
<!ELEMENT modulnr (#PCDATA)>
<!ELEMENT plan EMPTY>
	<!ATTLIST plan src CDATA #REQUIRED>
<!ELEMENT gleise (zulaufstrecken+,hgleise+,ngleise?)>
<!ELEMENT zulaufstrecken (links*,rechts*)>
<!ELEMENT links (#PCDATA)>
	<!ATTLIST links nr CDATA #REQUIRED>
<!ELEMENT rechts (#PCDATA)>
	<!ATTLIST rechts nr CDATA #REQUIRED>
<!ELEMENT hgleise (gleis+)>
<!ELEMENT ngleise (gleis+)>
<!ELEMENT gleis (name,laenge,bemerkung?)>
	<!ATTLIST gleis id ID #IMPLIED>
<!ELEMENT laenge (#PCDATA)>
	<!ATTLIST laenge einheit (mm|cm|achsen) "mm">
<!ELEMENT pv (bahnsteig+,bemerkung?)>
<!ELEMENT bahnsteig (name?,laenge)>
	<!ATTLIST bahnsteig gleis IDREFS #REQUIRED>
<!ELEMENT bemerkung (#PCDATA)>
<!ELEMENT gv (ladestelle+,verlader+,bemerkung?)>
<!ELEMENT ladestelle (name,laenge)>
	<!ATTLIST ladestelle id ID #IMPLIED>
	<!ATTLIST ladestelle gleis IDREFS #REQUIRED>
<!ELEMENT verlader (name,empfang?,versand?)>
<!ELEMENT empfang (ladegut+)>
<!ELEMENT ladegut (name,gattung,wagen)>
	<!ATTLIST ladegut ladestelle IDREFS #REQUIRED>
	<!ATTLIST ladegut typ (normal|stueckgut|expressgut) "normal">
<!ELEMENT gattung (#PCDATA)>
<!ELEMENT wagen (#PCDATA)>
	<!ATTLIST wagen zeitraum (tag|woche) "woche">
<!ELEMENT versand (ladegut+)>

=== fktt-module/datasheets/alt.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<bahnhof>
  <name>Altenstein</name>
  <kuerzel>ALT</kuerzel>
  <typ>Bf</typ>
  <verwaltung>DB</verwaltung>
  <maszstab>120.0</maszstab>
  <modulnr>GeReh203</modulnr>
  <plan src="alt.jpg" />
  <gleise>
    <zulaufstrecken />
    <hgleise>
      <gleis id="gleis_1">
        <name>1</name>
        <laenge>1160.0</laenge>
        <bemerkung>Durchgangsgleis (durchgehender Güter-/Personenverkehr aus Richtung Westen)</bemerkung>
      </gleis>
      <gleis id="gleis_2">
        <name>2</name>
        <laenge>1100.0</laenge>
        <bemerkung>Kreuzungsgleis (durchgehender Güter-/Personenverkehr aus Richtung Osten)</bemerkung>
      </gleis>
      <gleis id="gleis_3-33">
        <name>3-33</name>
        <laenge>630.0</laenge>
        <bemerkung>endender Personenverkehr aus Richtung Westen</bemerkung>
      </gleis>
    </hgleise>
    <ngleise>
      <gleis id="gleis_12">
        <name>12</name>
        <laenge>260.0</laenge>
        <bemerkung>Abstellgleis</bemerkung>
      </gleis>
      <gleis id="gleis_22">
        <name>22</name>
        <laenge>410.0</laenge>
        <bemerkung>Abstellgleis</bemerkung>
      </gleis>
      <gleis id="gleis_13">
        <name>13</name>
        <laenge>360.0</laenge>
        <bemerkung>Ladestraße I</bemerkung>
      </gleis>
      <gleis id="gleis_4">
        <name>4</name>
        <laenge>160.0</laenge>
        <bemerkung>Bereitstellung Güterwagen</bemerkung>
      </gleis>
      <gleis id="gleis_24">
        <name>24</name>
        <laenge>160.0</laenge>
        <bemerkung>Lokeinsatzstelle (Lokschuppen)</bemerkung>
      </gleis>
      <gleis id="gleis_5">
        <name>5</name>
        <laenge>240.0</laenge>
        <bemerkung>Ladestraße II / Lademaß, Waage</bemerkung>
      </gleis>
      <gleis id="gleis_15">
        <name>15</name>
        <laenge>160.0</laenge>
        <bemerkung>Kopf- und Seitenrampe, Viehverladung</bemerkung>
      </gleis>
      <gleis id="gleis_6">
        <name>6</name>
        <laenge>600.0</laenge>
        <bemerkung>Lokverkehrsgleis</bemerkung>
      </gleis>
      <gleis id="gleis_16">
        <name>16</name>
        <laenge>180.0</laenge>
        <bemerkung>Anschlussgleis Fa. Lampen Apparatebau</bemerkung>
      </gleis>
      <gleis id="gleis_25">
        <name>25</name>
        <laenge>180.0</laenge>
        <bemerkung>Güterschuppen</bemerkung>
      </gleis>
    </ngleise>
  </gleise>
  <pv>
    <bahnsteig gleis="gleis_3-33">
      <name>A - Hausbahnsteig</name>
      <laenge>630.0</laenge>
    </bahnsteig>
    <bahnsteig gleis="gleis_1">
      <name>B - Zwischenbahnsteig</name>
      <laenge>1160.0</laenge>
    </bahnsteig>
    <bahnsteig gleis="gleis_2">
      <name>C - Zwischenbahnsteig</name>
      <laenge>1100.0</laenge>
    </bahnsteig>
    <bemerkung>Berufs- und Schülerverkehr</bemerkung>
  </pv>
  <gv>
    <ladestelle id="Ladestra_e_I" gleis="gleis_13">
      <name>Ladestraße I</name>
      <laenge>360.0</laenge>
    </ladestelle>
    <ladestelle id="Ladestra_e_II_Waage_Ladema_" gleis="gleis_5">
      <name>Ladestraße II, Waage, / Lademaß</name>
      <laenge>170.0</laenge>
    </ladestelle>
    <ladestelle id="Laderampe" gleis="gleis_15">
      <name>Laderampe</name>
      <laenge>80.0</laenge>
    </ladestelle>
    <ladestelle id="Viehverladung" gleis="gleis_15">
      <name>Viehverladung</name>
      <laenge>80.0</laenge>
    </ladestelle>
    <ladestelle id="G_terschuppen_St_ckgut_" gleis="gleis_25">
      <name>Güterschuppen (Stückgut)</name>
      <laenge>180.0</laenge>
    </ladestelle>
    <ladestelle id="Fa._Lampen_Apparatebau" gleis="gleis_16">
      <name>Fa. Lampen Apparatebau</name>
      <laenge>180.0</laenge>
    </ladestelle>
    <ladestelle id="Kohlebansen" gleis="gleis_24">
      <name>Kohlebansen</name>
      <laenge>160.0</laenge>
    </ladestelle>
    <verlader>
      <name>Peter Lampen GmbH &amp; Co. KG, Feinmechanische Werkstatt</name>
      <empfang>
        <ladegut ladestelle="Fa._Lampen_Apparatebau">
          <name>Kunststoffhalbzeuge, Metallhalbzeuge</name>
          <gattung>G, H</gattung>
          <wagen>1.0</wagen>
        </ladegut>
        <ladegut ladestelle="Fa._Lampen_Apparatebau">
          <name>Holzbretter, Holzleisten für Transportverpackungen</name>
          <gattung>E, G, H, R, S</gattung>
          <wagen>1.0</wagen>
        </ladegut>
        <ladegut ladestelle="Fa._Lampen_Apparatebau">
          <name>Baulelemente</name>
          <gattung>G, H</gattung>
          <wagen>1.0</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Laderampe">
          <name>Apparate</name>
          <gattung>G, H, R, S</gattung>
          <wagen>1.0</wagen>
        </ladegut>
      </versand>
    </verlader>
    <verlader>
      <name>Heinrich Stiebe, Brennstoffhandel</name>
      <empfang>
        <ladegut ladestelle="Ladestra_e_I">
          <name>Eierkohlen, Briketts</name>
          <gattung>E</gattung>
          <wagen>5.0</wagen>
        </ladegut>
        <ladegut ladestelle="Ladestra_e_I">
          <name>Heizöl in Fässern</name>
          <gattung>E</gattung>
          <wagen>3.0</wagen>
        </ladegut>
      </empfang>
    </verlader>
    <verlader>
      <name>Senffabrik Finkenburg OHG</name>
      <empfang>
        <ladegut ladestelle="Laderampe">
          <name>Senfkörner Zucker (gesackt)</name>
          <gattung>G, H</gattung>
          <wagen>5.0</wagen>
        </ladegut>
        <ladegut ladestelle="Ladestra_e_II_Waage_Ladema_">
          <name>Wein in Fässern</name>
          <gattung>G, H</gattung>
          <wagen>3.0</wagen>
        </ladegut>
        <ladegut ladestelle="Laderampe">
          <name>Etikettiermaschinen, Verpackungsmaschinen</name>
          <gattung>R, S</gattung>
          <wagen>1.0</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Laderampe">
          <name>Senferzeugnisse</name>
          <gattung>G, H</gattung>
          <wagen zeitraum="tag">1.0</wagen>
        </ladegut>
      </versand>
    </verlader>
    <verlader>
      <name>Bauerngenossenschaft Altensteiner Land e.G.</name>
      <empfang>
        <ladegut ladestelle="Ladestra_e_I">
          <name>Düngemittel, lose</name>
          <gattung>T</gattung>
          <wagen>2.0</wagen>
        </ladegut>
        <ladegut ladestelle="G_terschuppen_St_ckgut_" typ="stueckgut">
          <name>Saatgut, gesackt als Stückgut</name>
          <gattung>G, H</gattung>
          <wagen>3.0</wagen>
        </ladegut>
        <ladegut ladestelle="G_terschuppen_St_ckgut_" typ="stueckgut">
          <name>Futtermittel, gesackt als Stückgut</name>
          <gattung>G, H</gattung>
          <wagen>3.0</wagen>
        </ladegut>
        <ladegut ladestelle="Viehverladung">
          <name>Jungvieh</name>
          <gattung>V</gattung>
          <wagen>2.0</wagen>
        </ladegut>
        <ladegut ladestelle="Laderampe">
          <name>Landmaschinen</name>
          <gattung>E, R, S</gattung>
          <wagen>1.0</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Ladestra_e_I">
          <name>Äpfel</name>
          <gattung>E</gattung>
          <wagen>1.0</wagen>
        </ladegut>
        <ladegut ladestelle="Ladestra_e_I">
          <name>Zuckerrüben</name>
          <gattung>E</gattung>
          <wagen>1.0</wagen>
        </ladegut>
        <ladegut ladestelle="Viehverladung">
          <name>Schlachtrinder, Schlachtschweine</name>
          <gattung>G, V</gattung>
          <wagen>3.0</wagen>
        </ladegut>
        <ladegut ladestelle="Ladestra_e_II_Waage_Ladema_" typ="expressgut">
          <name>Frischgemüse, Schnittblumen als Eilgut</name>
          <gattung>G, H</gattung>
          <wagen zeitraum="tag">1.0</wagen>
        </ladegut>
      </versand>
    </verlader>
    <verlader>
      <name>Lokeinsatzstelle</name>
      <empfang>
        <ladegut ladestelle="Kohlebansen">
          <name>Lokkohle</name>
          <gattung>E</gattung>
          <wagen zeitraum="tag">1.0</wagen>
        </ladegut>
        <ladegut ladestelle="Kohlebansen">
          <name>Ersatzteile</name>
          <gattung>G, K, X</gattung>
          <wagen>1.0</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Kohlebansen">
          <name>Altöl in Fässern</name>
          <gattung>G</gattung>
          <wagen>1.0</wagen>
        </ladegut>
        <ladegut ladestelle="Kohlebansen">
          <name>Tauschteile</name>
          <gattung>E, K, X</gattung>
          <wagen>1.0</wagen>
        </ladegut>
        <ladegut ladestelle="Laderampe">
          <name>Schlacke</name>
          <gattung>E</gattung>
          <wagen zeitraum="tag">1.0</wagen>
        </ladegut>
      </versand>
    </verlader>
  </gv>
</bahnhof>

=== fktt-module/datasheets/nc.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<bahnhof>
  <name>Coburg</name>
  <kuerzel>NC</kuerzel>
  <typ>Sbf</typ>
  <verwaltung>DB</verwaltung>
  <maszstab>120</maszstab>
  <modulnr>RaBec102</modulnr>
  <plan src="nc.jpg" />
  <gleise>
    <zulaufstrecken>
      <rechts nr="1">1gl</rechts>
    </zulaufstrecken>
    <hgleise>
      <gleis id="gleis1">
        <name>1</name>
        <laenge einheit="mm">3200.0</laenge>
      </gleis>
      <gleis id="gleis2">
        <name>2</name>
        <laenge einheit="mm">3100.0</laenge>
      </gleis>
      <gleis id="gleis3">
        <name>3</name>
        <laenge einheit="mm">3000.0</laenge>
      </gleis>
      <gleis id="gleis4">
        <name>4</name>
        <laenge einheit="mm">2900.0</laenge>
      </gleis>
      <gleis id="gleis5">
        <name>5</name>
        <laenge einheit="mm">2800.0</laenge>
      </gleis>
    </hgleise>
  </gleise>
  <bemerkung>FY mit Rückmeldern[br]FY mit Anschluß an Rocrail</bemerkung>
</bahnhof>

=== fktt-module/datasheets/ren.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Rennsteig</name>
	<kuerzel>REN</kuerzel>
	<typ>Bf</typ>
	<verwaltung>DR</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>DiWan248</modulnr>
	<plan src="ren.gif"/>
	<gleise>
		<zulaufstrecken>
			<links nr="1">1gl</links>
			<links nr="2">1gl</links>
			<rechts nr="1">1gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis id="Bst2">
				<name>2</name>
				<laenge>1500</laenge>
				<bemerkung>Bahnsteiggleis</bemerkung>
			</gleis>
			<gleis id="Bst3">
				<name>3</name>
				<laenge>1300</laenge>
				<bemerkung>Bahnsteiggleis</bemerkung>
			</gleis>
			<gleis id="Kleinbahn">
				<name>6</name>
				<laenge>1000</laenge>
				<bemerkung>Ausfahrgleis, Bahnsteiggleis Kleinbahn</bemerkung>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis id="Ladestrasseg">
				<name>1</name>
				<laenge>900</laenge>
				<bemerkung>Güterschuppen, Ladestraße, Seitenrampe</bemerkung>
			</gleis>
			<gleis id="UGL">
				<name>4</name>
				<laenge>1000</laenge>
				<bemerkung>Umfahrungsgleis</bemerkung>
			</gleis>
			<gleis id="Uegl">
				<name>5</name>
				<laenge>1200</laenge>
				<bemerkung>Übergabegleis Kleinbahn</bemerkung>
			</gleis>
		</ngleise>
	</gleise>
	<pv>
		<bahnsteig gleis="Bst2">
			<name>2</name>
			<laenge>900</laenge>
		</bahnsteig>
		<bahnsteig gleis="Bst3">
			<name>3</name>
			<laenge>1050</laenge>
		</bahnsteig>
		<bahnsteig gleis="Kleinbahn">
			<name>6</name>
			<laenge>500</laenge>
		</bahnsteig>
		<bemerkung>Übergangsreisende, Urlauber, Wanderer, Vatertagsfreunde</bemerkung>
	</pv>
	<gv>
		<ladestelle id="Gueterschuppen" gleis="Ladestrasseg">
			<name>Güterschuppen (1a)</name>
			<laenge>200</laenge>
		</ladestelle>
		<ladestelle id="Ladestrasse" gleis="Ladestrasseg">
			<name>Ladestraße (1b)</name>
			<laenge>300</laenge>
		</ladestelle>
		<ladestelle id="Seitenrampe" gleis="Ladestrasseg">
			<name>Seitenrampe (1c)</name>
			<laenge>400</laenge>
		</ladestelle>
		<verlader>
			<name>Forstamt Rennsteig</name>
			<empfang>
				<ladegut ladestelle="Gueterschuppen">
					<name>Werkzeug</name>
					<gattung>G</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Seitenrampe">
					<name>Stammmholz</name>
					<gattung>E,X,R</gattung>
					<wagen zeitraum="tag">3</wagen>
				</ladegut>
				<ladegut ladestelle="Gueterschuppen">
					<name>Wild (Reh, Hirsch, Wildschwein)</name>
					<gattung>G, H,</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>VEB Glaskunst Lauscha BT II Rennsteig</name>
			<empfang>
				<ladegut ladestelle="Ladestrasse">
					<name>Sand</name>
					<gattung>L,R</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
				<ladegut ladestelle="Gueterschuppen">
					<name>Pottasche gesackt</name>
					<gattung>G</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Gueterschuppen">
					<name>Christbaumschmuck</name>
					<gattung>E</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>Ferienlager Wilhelm Pieck SDAG Wismut</name>
			<empfang>
				<ladegut ladestelle="Ladestrasse">
					<name>Kartoffeln lose</name>
					<gattung>G,E</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Gueterschuppen">
					<name>Gemüse</name>
					<gattung>H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Kleinvieh</name>
					<gattung>V</gattung>
					<wagen zeitraum="woche">0.5</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Rindvieh</name>
					<gattung>V</gattung>
					<wagen zeitraum="woche">0.5</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Kohle (Rohbraunkohle)</name>
					<gattung>E</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
			</empfang>
		</verlader>
		<verlader>
			<name>Stückgutschuppen</name>
			<empfang>
				<ladegut ladestelle="Gueterschuppen">
					<name>Stückgut, Expressgut</name>
					<gattung>G ,PWg</gattung>
					<wagen zeitraum="woche">7</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Gueterschuppen">
					<name>Stückgut, Expressgut</name>
					<gattung>G,Pwg</gattung>
					<wagen zeitraum="woche">7</wagen>
				</ladegut>
			</versand>
		</verlader>
		<bemerkung>Güterwagen für die Kleinbahn sind auf Gleis 5 abzustellen.</bemerkung>
	</gv>
	<bemerkung>Weichen der Kleinbahn bei Ausfahrt in Grundstellung.[br]Alle Züge müssen Kopf machen.</bemerkung>
</bahnhof>

=== fktt-module/datasheets/poe.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<bahnhof>
  <name>Pöhlau Güterbahnhof</name>
  <kuerzel>POE</kuerzel>
  <typ>Bf</typ>
  <verwaltung>DR</verwaltung>
  <maszstab>120.0</maszstab>
  <modulnr>BeKas247</modulnr>
  <plan src="poe.png" />
  <gleise>
    <zulaufstrecken>
      <links nr="1">IBahn</links>
      <rechts nr="1">IBahn</rechts>
    </zulaufstrecken>
    <hgleise>
      <gleis id="gleis_102">
        <name>102</name>
        <laenge einheit="mm">7000.0</laenge>
        <bemerkung>Durchfahrtsgleis Hauptbahn</bemerkung>
      </gleis>
      <gleis id="gleis_103">
        <name>103</name>
        <laenge einheit="mm">7000.0</laenge>
        <bemerkung>Durchfahrtsgleis Hauptbahn</bemerkung>
      </gleis>
      <gleis id="gleis_101">
        <name>101</name>
        <laenge einheit="mm">3000.0</laenge>
        <bemerkung>Zufuhrgleis</bemerkung>
      </gleis>
      <gleis id="gleis_100">
        <name>100</name>
        <laenge einheit="mm">3000.0</laenge>
        <bemerkung>Abfuhrgleis</bemerkung>
      </gleis>
      <gleis id="gleis_1">
        <name>1</name>
        <laenge einheit="mm">2800.0</laenge>
        <bemerkung>Aufstellgleis</bemerkung>
      </gleis>
      <gleis id="gleis_2">
        <name>2</name>
        <laenge einheit="mm">2500.0</laenge>
        <bemerkung>Aufstellgleis</bemerkung>
      </gleis>
      <gleis id="gleis_3">
        <name>3</name>
        <laenge einheit="mm">2500.0</laenge>
        <bemerkung>Aufstellgleis</bemerkung>
      </gleis>
      <gleis id="gleis_4">
        <name>4</name>
        <laenge einheit="mm">2000.0</laenge>
        <bemerkung>Lokumfahrgleis</bemerkung>
      </gleis>
    </hgleise>
    <ngleise>
      <gleis id="gleis_3a">
        <name>3a</name>
        <laenge einheit="mm">400.0</laenge>
        <bemerkung>Seitenrampe</bemerkung>
      </gleis>
      <gleis id="gleis_12">
        <name>12</name>
        <laenge einheit="mm">800.0</laenge>
        <bemerkung>Abstellgleis</bemerkung>
      </gleis>
      <gleis id="gleis_14">
        <name>14</name>
        <laenge einheit="mm">800.0</laenge>
        <bemerkung>Abstellgleis</bemerkung>
      </gleis>
      <gleis id="gleis_22">
        <name>22</name>
        <laenge einheit="mm">2000.0</laenge>
        <bemerkung>Abstellgleis BHG</bemerkung>
      </gleis>
      <gleis id="gleis_7">
        <name>7</name>
        <laenge einheit="mm">400.0</laenge>
        <bemerkung>WÜST</bemerkung>
      </gleis>
      <gleis id="gleis_8">
        <name>8</name>
        <laenge einheit="mm">400.0</laenge>
        <bemerkung>WÜST</bemerkung>
      </gleis>
      <gleis id="gleis_Schuppengleis">
        <name>Schuppengleis</name>
        <laenge einheit="mm">200</laenge>
        <bemerkung>Schuppen</bemerkung>
      </gleis>
      <gleis id="gleis_Tankgleis">
        <name>Tankgleis</name>
        <laenge einheit="mm">200</laenge>
        <bemerkung>Tankstelle</bemerkung>
      </gleis>
      <gleis id="gleis_Schweissplatz">
        <name>Schweissplatz</name>
        <laenge einheit="mm">200</laenge>
      </gleis>
    </ngleise>
  </gleise>
  <pv>
    <bahnsteig gleis="gleis_103">
      <name>Bahnsteig 1</name>
      <laenge einheit="mm">1800.0</laenge>
    </bahnsteig>
    <bahnsteig gleis="gleis_102">
      <name>Bahnsteig 2</name>
      <laenge einheit="mm">1800.0</laenge>
    </bahnsteig>
    <bemerkung>Haltepunkt für Arbeiter-, Berufs- und Ausflugsverkehr</bemerkung>
  </pv>
  <gv>
    <ladestelle id="Rampe" gleis="gleis_3a">
      <name>Rampe</name>
      <laenge einheit="mm">300</laenge>
    </ladestelle>
    <ladestelle id="Kohleverladung_1" gleis="gleis_7">
      <name>Kohleverladung 1</name>
      <laenge einheit="mm">800</laenge>
    </ladestelle>
    <ladestelle id="Kohlerverladung_2" gleis="gleis_8">
      <name>Kohlerverladung 2</name>
      <laenge einheit="mm">800</laenge>
    </ladestelle>
    <ladestelle id="Lokschuppen" gleis="gleis_22">
      <name>Lokschuppen</name>
      <laenge einheit="mm">200</laenge>
    </ladestelle>
    <verlader>
      <name>Verlader</name>
    </verlader>
  </gv>
  <bemerkung>Der Bahnhof dient als Sammelbahnhof für die angeschlossenen Betriebsstellen der  I-Bahn. Zur Zeit hat der Bahnhof  keinen eigenen Ladungsverkehr.[br]Bahnhof befindet sich derzeit im Aufbau. Rote Gleise nicht befahrbahr.</bemerkung>
</bahnhof>

=== fktt-module/datasheets/tbs.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Taubenstein</name>
	<kuerzel>TBS</kuerzel>
	<typ>Anst</typ>
	<verwaltung>DB</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>HeSch356</modulnr>
	<plan src="tbs.png" />
	<gleise>
		<zulaufstrecken>
			<links nr="1">1gl</links>
			<rechts nr="1">1gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis>
				<name>Strecke</name>
				<laenge einheit="cm">80</laenge>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis id="g2">
				<name>Anschluss</name>
				<laenge einheit="cm">50</laenge>
			</gleis>
		</ngleise>
	</gleise>
	<gv>
		<ladestelle id="rampe" gleis="g2">
			<name>Rampe</name>
			<laenge einheit="cm">45</laenge>
		</ladestelle>
		<verlader>
			<name>Schlachthof "G.Flügel"</name>
			<empfang>
				<ladegut ladestelle="rampe">
					<name>Geflügel</name>
					<gattung>V, G</gattung>
					<wagen zeitraum="tag">2</wagen>
				</ladegut>
				<ladegut ladestelle="rampe">
					<name>Propangas</name>
					<gattung>Z</gattung>
					<wagen>1</wagen>
				</ladegut>
				<ladegut ladestelle="rampe">
					<name>Trockeneis</name>
					<gattung>I</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="rampe">
					<name>Gewürze</name>
					<gattung>Stückgut</gattung>
					<wagen>2</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="rampe">
					<name>Frischgeflügel</name>
					<gattung>I, T</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
				<ladegut ladestelle="rampe">
					<name>Gefriergeflügel</name>
					<gattung>I, T</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
				<ladegut ladestelle="rampe">
					<name>Schlachtabfälle</name>
					<gattung>O, E</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
			</versand>
		</verlader>
	</gv>
</bahnhof>

=== fktt-module/datasheets/suk.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Schurkau</name>
	<kuerzel>SUK</kuerzel>
	<typ>Hp</typ>
	<verwaltung>DB</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>MBGMu819</modulnr>
	<plan src="suk.png" />
	<gleise>
		<zulaufstrecken>
			<links nr="1">2gl</links>
			<links nr="2">2gl</links>
			<rechts nr="1">2gl</rechts>
			<rechts nr="2">2gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis id="hg1">
				<name>1</name>
				<laenge einheit="cm">100</laenge>
			</gleis>
			<gleis id="hg2">
				<name>2</name>
				<laenge einheit="cm">100</laenge>
			</gleis>
		</hgleise>
	</gleise>
	<pv>
		<bahnsteig gleis="hg1">
			<laenge einheit="cm">100</laenge>
		</bahnsteig>
		<bahnsteig gleis="hg2">
			<laenge einheit="cm">100</laenge>
		</bahnsteig>
	</pv>
</bahnhof>

=== fktt-module/datasheets/pyt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Anst. Pyrotechnik</name>
	<kuerzel>PYT</kuerzel>
	<typ>Anst</typ>
	<verwaltung>DR</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>JuUhl350</modulnr>
	<plan src="pyt.jpg"/>
	<gleise>
		<zulaufstrecken>
			<links nr="1">1gl</links>
			<rechts nr="1">1gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis id="hg1">
				<name>1</name>
				<laenge>400</laenge>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis id="A1">
				<name>A1</name>
				<laenge>400</laenge>
				<bemerkung>Verladeschuppen</bemerkung>
			</gleis>
			<gleis id="A2">
				<name>A2</name>
				<laenge>150</laenge>
			</gleis>
		</ngleise>
	</gleise>
	<gv>
		<ladestelle id="Verladeschuppen" gleis="A1">
			<name>Verladeschuppen</name>
			<laenge>150</laenge>
		</ladestelle>
		<verlader>
			<name>Pyrotechnisches Lager</name>
			<empfang>
				<ladegut ladestelle="Verladeschuppen">
					<name>Feuerwerkskörper</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Sprengstoff</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">4</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Munition</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Zement</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Bausand</name>
					<gattung>E, K</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Bauholz</name>
					<gattung>K, R</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Verladeschuppen">
					<name>pyrotechnische Erzeugnisse</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Sprengstoff</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">3</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Sondermüll</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Verladeschuppen">
					<name>Munition für KK-Waffen</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</versand>
		</verlader>
		<bemerkung>Alle Wagen mit Explosivstoffen werden durch Mitarbeiter der Trapo begleitet (Begleitwagen beigeben).</bemerkung>
	</gv>
</bahnhof>
