=== fktt-module/datasheets/bahnhof.dtd
<!ELEMENT bahnhof (name,kuerzel,typ,verwaltung,maszstab,modulnr,plan?,gleise,pv?,gv?,bemerkung?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT kuerzel (#PCDATA)>
<!ELEMENT typ (#PCDATA)>
<!ELEMENT verwaltung (#PCDATA)>
<!ELEMENT maszstab (#PCDATA)>
<!ELEMENT modulnr (#PCDATA)>
<!ELEMENT plan EMPTY>
	<!ATTLIST plan src CDATA #REQUIRED>
<!ELEMENT gleise (zulaufstrecken+,hgleise+,ngleise?)>
<!ELEMENT zulaufstrecken (links*,rechts*)>
<!ELEMENT links (#PCDATA)>
	<!ATTLIST links nr CDATA #REQUIRED>
<!ELEMENT rechts (#PCDATA)>
	<!ATTLIST rechts nr CDATA #REQUIRED>
<!ELEMENT hgleise (gleis+)>
<!ELEMENT ngleise (gleis+)>
<!ELEMENT gleis (name,laenge,bemerkung?)>
	<!ATTLIST gleis id ID #IMPLIED>
<!ELEMENT laenge (#PCDATA)>
	<!ATTLIST laenge einheit (mm|cm|achsen) "mm">
<!ELEMENT pv (bahnsteig+,bemerkung?)>
<!ELEMENT bahnsteig (name?,laenge)>
	<!ATTLIST bahnsteig gleis IDREFS #REQUIRED>
<!ELEMENT bemerkung (#PCDATA)>
<!ELEMENT gv (ladestelle+,verlader+,bemerkung?)>
<!ELEMENT ladestelle (name,laenge)>
	<!ATTLIST ladestelle id ID #IMPLIED>
	<!ATTLIST ladestelle gleis IDREFS #REQUIRED>
<!ELEMENT verlader (name,empfang?,versand?)>
<!ELEMENT empfang (ladegut+)>
<!ELEMENT ladegut (name,gattung,wagen)>
	<!ATTLIST ladegut ladestelle IDREFS #REQUIRED>
	<!ATTLIST ladegut typ (normal|stueckgut|expressgut) "normal">
<!ELEMENT gattung (#PCDATA)>
<!ELEMENT wagen (#PCDATA)>
	<!ATTLIST wagen zeitraum (tag|woche) "woche">
<!ELEMENT versand (ladegut+)>

=== fktt-module/datasheets/spz.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Spitz</name>
	<kuerzel>SPZ</kuerzel>
	<typ>Bf</typ>
	<verwaltung>DR</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>UdSpi255</modulnr>
	<plan src="spz.png" />
	<gleise>
		<zulaufstrecken>
			<links nr="1">1gl</links>
			<rechts nr="1">1gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis>
				<name>1</name>
				<laenge einheit="cm">220</laenge>
				<bemerkung>Güterzuggleis</bemerkung>
			</gleis>
			<gleis id="hg2">
				<name>2</name>
				<laenge einheit="cm">210</laenge>
				<bemerkung>durchgehendes Hauptgleis</bemerkung>
			</gleis>
			<gleis id="hg3">
				<name>3</name>
				<laenge einheit="cm">205</laenge>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis>
				<name>1b</name>
				<laenge einheit="cm">40</laenge>
			</gleis>
			<gleis id="ladegleis">
				<name>4</name>
				<laenge einheit="cm">150</laenge>
				<bemerkung>Ladestraße mit Güterschuppen</bemerkung>
			</gleis>
			<gleis id="heizgleis">
				<name>5a</name>
				<laenge einheit="cm">75</laenge>
				<bemerkung>Anschlussgleis Heizwerk</bemerkung>
			</gleis>
			<gleis id="maschgleis">
				<name>5b</name>
				<laenge einheit="cm">65</laenge>
				<bemerkung>Anschlussgleis Maschinenfabrik</bemerkung>
			</gleis>
			<gleis>
				<name>6</name>
				<laenge einheit="cm">65</laenge>
				<bemerkung>Ziehgleis und Abstellgleis</bemerkung>
			</gleis>
		</ngleise>
	</gleise>
	<pv>
		<bahnsteig gleis="hg2">
			<name>1</name>
			<laenge einheit="cm">175</laenge>
		</bahnsteig>
		<bahnsteig gleis="hg3">
			<name>2</name>
			<laenge einheit="cm">175</laenge>
		</bahnsteig>
	</pv>
	<gv>
		<ladestelle id="ladestr" gleis="ladegleis">
			<name>Ladestraße</name>
			<laenge einheit="cm">133</laenge>
		</ladestelle>
		<ladestelle id="gschuppen" gleis="ladegleis">
			<name>Güterschuppen</name>
			<laenge einheit="cm">17</laenge>
		</ladestelle>
		<ladestelle id="maschinenfabrik" gleis="maschgleis">
			<name>Anschluss Maschinenfabrik</name>
			<laenge einheit="cm">65</laenge>
		</ladestelle>
		<ladestelle id="heizwerk" gleis="heizgleis">
			<name>Anschluss Heizwerk</name>
			<laenge einheit="cm">75</laenge>
		</ladestelle>
		<verlader>
			<name>VEB Chemische Werke Spitz - Fettchemie</name>
			<empfang>
				<ladegut ladestelle="ladestr">
					<name>Öle</name>
					<gattung>Z, G</gattung>
					<wagen>5</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>chemische Produkte</name>
					<gattung>E, G</gattung>
					<wagen>3</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="ladestr">
					<name>Fette</name>
					<gattung>G</gattung>
					<wagen>5</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Öle</name>
					<gattung>Z, G</gattung>
					<wagen>10</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>VEB Büromaschinen Sömmerda, Außenstelle Spitz</name>
			<empfang>
				<ladegut ladestelle="gschuppen">
					<name>Maschinenelemente</name>
					<gattung>G, H</gattung>
					<wagen>3</wagen>
				</ladegut>
				<ladegut ladestelle="gschuppen">
					<name>Bleche</name>
					<gattung>G, H</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="gschuppen">
					<name>elektronische Bauteile</name>
					<gattung>G, H</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="gschuppen">
					<name>Monitore</name>
					<gattung>G, H</gattung>
					<wagen>2</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="gschuppen">
					<name>Großrechenanlagen</name>
					<gattung>G, H</gattung>
					<wagen>5</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>VEB Fräs- und Drehmaschinenbau "Hans Beimler"</name>
			<empfang>
				<ladegut ladestelle="maschinenfabrik">
					<name>Coils</name>
					<gattung>R, S</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="maschinenfabrik">
					<name>Maschinenelemente</name>
					<gattung>G, R, S</gattung>
					<wagen>2</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="maschinenfabrik">
					<name>Werkzeugmaschinen</name>
					<gattung>G, R, S</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="maschinenfabrik">
					<name>Metallspäne</name>
					<gattung>E</gattung>
					<wagen>2</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>BHG Spitz</name>
			<empfang>
				<ladegut ladestelle="gschuppen">
					<name>Dünger</name>
					<gattung>G</gattung>
					<wagen>3</wagen>
				</ladegut>
				<ladegut ladestelle="gschuppen">
					<name>Saatgut</name>
					<gattung>G</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="gschuppen">
					<name>Maschinen</name>
					<gattung>G, R, S</gattung>
					<wagen>1</wagen>
				</ladegut>
				<ladegut ladestelle="gschuppen">
					<name>Briketts</name>
					<gattung>E, F</gattung>
					<wagen>3</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="gschuppen">
					<name>Landwirtschaftsprodukte</name>
					<gattung>G, F</gattung>
					<wagen>10</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>VEB Rohrleitungsbau Spitz</name>
			<empfang>
				<ladegut ladestelle="ladestr">
					<name>Coils</name>
					<gattung>R, S</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Halbzeuge</name>
					<gattung>R, S</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Rohre</name>
					<gattung>R, S</gattung>
					<wagen>2</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="ladestr">
					<name>Stahlrohre</name>
					<gattung>R, S</gattung>
					<wagen>4</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>Heizwerk Spitz</name>
			<empfang>
				<ladegut ladestelle="heizwerk">
					<name>Kohle</name>
					<gattung>E, F</gattung>
					<wagen>14</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="heizwerk">
					<name>Asche</name>
					<gattung>U</gattung>
					<wagen>5</wagen>
				</ladegut>
			</versand>
		</verlader>
	</gv>
</bahnhof>

=== fktt-module/datasheets/kfd-VI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
  <name>Kranichsfeld</name>
  <kuerzel>KFD</kuerzel>
  <typ>Bf</typ>
  <verwaltung>DR</verwaltung>
  <maszstab>120</maszstab>
  <modulnr>JuUhl235</modulnr>
  <plan src="kfd.jpg" />
  <gleise>
    <zulaufstrecken>
      <links nr="1">1gl</links>
      <rechts nr="1">1gl</rechts>
    </zulaufstrecken>
    <hgleise>
      <gleis id="Gleis_1b">
        <name>1b</name>
        <laenge einheit="mm">1800</laenge>
        <bemerkung>Ein- und Ausfahrgleis</bemerkung>
      </gleis>
      <gleis id="Gleis_3b">
        <name>3b</name>
        <laenge einheit="mm">1550</laenge>
        <bemerkung>Ein- und Ausfahrgleis für Güterzüge</bemerkung>
      </gleis>
      <gleis id="Gleis_5">
        <name>5</name>
        <laenge einheit="mm">1600</laenge>
        <bemerkung>Ein- und Ausfahrgleis für Güterzüge</bemerkung>
      </gleis>
      <gleis id="Gleis_1a">
        <name>1a</name>
        <laenge einheit="mm">840.0</laenge>
        <bemerkung>Hausbahnsteig</bemerkung>
      </gleis>
    </hgleise>
    <ngleise>
      <gleis id="Gleis_2a">
        <name>2a</name>
        <laenge einheit="mm">500</laenge>
        <bemerkung>Einsatzstelle mit Triebwagenschuppen</bemerkung>
      </gleis>
      <gleis id="Gleis_2b">
        <name>2b</name>
        <laenge einheit="mm">1300</laenge>
        <bemerkung>Umfahrgleis</bemerkung>
      </gleis>
      <gleis id="Gleis_3a">
        <name>3a</name>
        <laenge einheit="mm">150</laenge>
        <bemerkung>Seitenrampe</bemerkung>
      </gleis>
      <gleis id="Gleis_3c">
        <name>3c</name>
        <laenge einheit="mm">650</laenge>
        <bemerkung>Güterschuppen</bemerkung>
      </gleis>
      <gleis id="Gleis_4">
        <name>4</name>
        <laenge einheit="mm">1700</laenge>
        <bemerkung>Ladestraße/Freiladegleis und Kopframpe</bemerkung>
      </gleis>
      <gleis id="Gleis_A1">
        <name>A1</name>
        <laenge einheit="mm">350.0</laenge>
        <bemerkung>Sammelgleis Salzsäure</bemerkung>
      </gleis>
      <gleis id="gleisA2">
        <name>A2</name>
        <laenge einheit="mm">370.0</laenge>
        <bemerkung>Abfüll- und Entladestelle Salzsäure</bemerkung>
      </gleis>
    </ngleise>
  </gleise>
  <pv>
    <bahnsteig gleis="Gleis_1a">
      <name>Hausbahnsteig</name>
      <laenge einheit="mm">800</laenge>
    </bahnsteig>
    <bemerkung>Taktverkehr in der Regel mit Triebwagen prägen das Vorbild in der Zeit ab 1995. In der Folge wird der Bahnhof zum Haltepunkt umgebaut.[br]Bei eingeschränktem Güterverkehr kann das Güterschuppengleis als Bahnsteiggleis für kurze Züge oder Triebwagen genutzt werden. Beachte dann aber die Ausfahrrichtung.</bemerkung>
  </pv>
  <gv>
    <ladestelle id="Kopframpe" gleis="Gleis_4">
      <name>Kopframpe</name>
      <laenge einheit="mm">200</laenge>
    </ladestelle>
    <ladestelle id="Seitenrampe" gleis="Gleis_3a">
      <name>Seitenrampe</name>
      <laenge einheit="mm">150</laenge>
    </ladestelle>
    <ladestelle id="Ladestraße" gleis="Gleis_4">
      <name>Ladestraße</name>
      <laenge einheit="mm">1500</laenge>
    </ladestelle>
    <ladestelle id="Güterschuppen" gleis="Gleis_3c">
      <name>Güterschuppen</name>
      <laenge einheit="mm">450.0</laenge>
    </ladestelle>
    <ladestelle id="Einsatzstelle" gleis="Gleis_2a">
      <name>Einsatzstelle</name>
      <laenge einheit="mm">500</laenge>
    </ladestelle>
    <ladestelle id="Valentin_Fl_ssiggas" gleis="Gleis_A1">
      <name>Valentin Flüssiggas</name>
      <laenge einheit="mm">370.0</laenge>
    </ladestelle>
    <ladestelle id="Entladestelle_Valentin_Fl_ssiggas" gleis="gleisA2">
      <name>Entladestelle Valentin Flüssiggas</name>
      <laenge einheit="mm">350.0</laenge>
    </ladestelle>
    <verlader>
      <name>Kabel-AG, Werk Kranichsfeld</name>
      <empfang>
        <ladegut ladestelle="Ladestraße">
          <name>Plastgranulat</name>
          <gattung>H</gattung>
          <wagen zeitraum="woche">2</wagen>
        </ladegut>
        <ladegut ladestelle="Ladestraße">
          <name>Leitungskupfer</name>
          <gattung>H</gattung>
          <wagen zeitraum="woche">1</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Ladestraße">
          <name>Installationskabel</name>
          <gattung>H</gattung>
          <wagen zeitraum="woche">2.0</wagen>
        </ladegut>
      </versand>
    </verlader>
    <verlader>
      <name>Forstwirtschaftsbetrieb Kranichsfeld</name>
      <empfang>
        <ladegut ladestelle="Ladestraße">
          <name>Pestizide</name>
          <gattung>Z/G/H</gattung>
          <wagen zeitraum="woche">1</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Ladestraße">
          <name>Stammholz</name>
          <gattung>E/R/S</gattung>
          <wagen zeitraum="woche">3</wagen>
        </ladegut>
        <ladegut ladestelle="Ladestraße">
          <name>Rindenmulch</name>
          <gattung>E</gattung>
          <wagen zeitraum="woche">1</wagen>
        </ladegut>
      </versand>
    </verlader>
    <verlader>
      <name>Schraubenwerk Kranichsfeld</name>
      <empfang>
        <ladegut ladestelle="Ladestraße">
          <name>Rundstahl</name>
          <gattung>X/E/R</gattung>
          <wagen zeitraum="woche">1</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Ladestraße">
          <name>Schrauben, Muttern</name>
          <gattung>G/H</gattung>
          <wagen zeitraum="woche">2</wagen>
        </ladegut>
        <ladegut ladestelle="Kopframpe">
          <name>Holzschrauben</name>
          <gattung>Container</gattung>
          <wagen zeitraum="woche">1</wagen>
        </ladegut>
      </versand>
    </verlader>
    <verlader>
      <name>Agrargenossenschaft Kranichsfeld</name>
      <empfang>
        <ladegut ladestelle="Ladestraße">
          <name>Saatgut</name>
          <gattung>G/H/T</gattung>
          <wagen zeitraum="woche">1</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="Ladestraße">
          <name>Getreide</name>
          <gattung>G/H/T</gattung>
          <wagen zeitraum="woche">4</wagen>
        </ladegut>
        <ladegut ladestelle="Ladestraße">
          <name>Braugerste</name>
          <gattung>G/H/Container</gattung>
          <wagen zeitraum="woche">1</wagen>
        </ladegut>
      </versand>
    </verlader>
    <verlader>
      <name>Valentin Flüssiggas</name>
      <empfang>
        <ladegut ladestelle="Entladestelle_Valentin_Fl_ssiggas">
          <name>Flüssiggas</name>
          <gattung>Z</gattung>
          <wagen>3</wagen>
        </ladegut>
      </empfang>
    </verlader>
    <bemerkung>Landwirtschaft, Kabelwerk, Schraubenwerk, Forstwirtschaft, Flüssiggashändler</bemerkung>
  </gv>
  <bemerkung>Der Endbahnhof der Ilmtalbahn Kranichfeld diente als erstes Vorbild für den Modulbahnhof. Inzwischen hat der Bahnhof etliche Erweiterungen erfahren und kann auch als Durchgangsbahnhof betrieben werden.</bemerkung>
</bahnhof>

=== fktt-module/datasheets/ahw.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Holzwerk</name>
	<kuerzel>AHW</kuerzel>
	<typ>Anschl</typ>
	<maszstab>120</maszstab>
	<modulnr>MiSch393</modulnr>
	<plan src="ahw.svg"/>
	<gleise>
		<zulaufstrecken>
			<links nr="1">1gl</links>
			<rechts nr="1">1gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis id="Bahnsteiggleis">
				<name>Streckengleis</name>
				<laenge>2000</laenge>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis id="gleis_1">
				<name>1</name>
				<laenge>1330</laenge>
			</gleis>
			<gleis id="gleis_2">
				<name>2</name>
				<laenge>1330</laenge>
			</gleis>
		</ngleise>
	</gleise>
	<gv>
		<ladestelle id="Kranverladung" gleis="gleis_1 gleis_2">
			<name>Kranverladung</name>
			<laenge> </laenge>
		</ladestelle>
		<verlader>
			<name>Holzwerk</name>
			<versand>
				<ladegut ladestelle="Kranverladung">
					<name>Stammholz</name>
					<gattung>K, R, Eas</gattung>
					<wagen zeitraum="tag">10</wagen>
				</ladegut>
				<ladegut ladestelle="Kranverladung">
					<name>Bretter</name>
					<gattung>K, R, Eas</gattung>
					<wagen zeitraum="tag">10</wagen>
				</ladegut>
			</versand>
		</verlader>
	</gv>
</bahnhof>

=== fktt-module/datasheets/amr.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./bahnhof.xsl" type="text/xsl"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<bahnhof>
  <name>Motorenreparatur</name>
  <kuerzel>AMR</kuerzel>
  <typ>Anst</typ>
  <verwaltung>DR</verwaltung>
  <maszstab>120</maszstab>
  <modulnr>MaRue370</modulnr>
  <plan src="amr.svg"/>
  <gleise>
    <zulaufstrecken>
      <links nr="1">1gl</links>
    </zulaufstrecken>
    <hgleise>
      <gleis id="strecke">
        <name>Streckengleis</name>
        <laenge>350</laenge>
      </gleis>
    </hgleise>
  </gleise>
  <gv>
    <ladestelle id="l" gleis="strecke">
      <name>Laderampe</name>
      <laenge>200</laenge>
    </ladestelle>
    <verlader>
      <name>Reiman Motoren PGH</name>
      <empfang>
        <ladegut ladestelle="l">
          <name>Elektromotoren zur Reparatur</name>
          <gattung>E, R</gattung>
          <wagen>1</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="l">
          <name>Elektromotoren zur Reparatur</name>
          <gattung>E, R</gattung>
          <wagen>1</wagen>
        </ladegut>
      </versand>
    </verlader>
  </gv>
</bahnhof>

=== fktt-module/datasheets/gud.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
  <name>Guddenberg</name>
  <kuerzel>GUD</kuerzel>
  <typ>Sbf</typ>
  <verwaltung>DR</verwaltung>
  <maszstab>120</maszstab>
  <modulnr>MaRue105</modulnr>
  <plan src="gud.svg"/>
  <gleise>
    <zulaufstrecken>
      <links nr="1">1gl</links>
    </zulaufstrecken>
    <hgleise>
      <gleis id="gl1">
        <name>1</name>
        <laenge>2200</laenge>
      </gleis>
      <gleis id="gl2">
        <name>2</name>
        <laenge>2000</laenge>
      </gleis>
      <gleis id="gl3">
        <name>3</name>
        <laenge>2000</laenge>
      </gleis>
      <gleis id="gl4">
        <name>4</name>
        <laenge>2000</laenge>
      </gleis>
      <gleis id="gl5">
        <name>5</name>
        <laenge>2000</laenge>
      </gleis>
      <gleis id="gl6">
        <name>6</name>
        <laenge>2100</laenge>
      </gleis>
      <gleis id="gl7">
        <name>7</name>
        <laenge>2100</laenge>
      </gleis>
    </hgleise>
  </gleise>
  <bemerkung>Die Gleisnutzlänge hängt von der Aufbaulänge ab. Angegebene Maße beziehen sich auf den kompletten Aufbau mit einer Gesamtlänge von 2700mm.[br][br]Aufbaulänge um 900mm reduzierbar.</bemerkung>
</bahnhof>

=== fktt-module/datasheets/okw.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
   <name>Abzweig Oberkaselwitz</name>
   <kuerzel>OKW</kuerzel>
   <typ>Abzw</typ>
   <verwaltung>DB</verwaltung>
   <maszstab>120</maszstab>
   <modulnr>RaGra405</modulnr>
   <plan src="okw.png"/>
   <gleise>
		<zulaufstrecken>
			<links nr="1">2gl</links>
			<links nr="2">1gl</links>
			<links nr="3">IBahn</links>
			<rechts nr="1">2gl</rechts>
		</zulaufstrecken>
	<hgleise>
      <gleis id="Innenbogen">
         <name>1</name>
         <laenge>2000</laenge>
      </gleis>
      <gleis id="Aussenbogen">
         <name>2</name>
         <laenge>2000</laenge>
      </gleis>
      <gleis id="IBahn">
         <name>3</name>
         <laenge>800</laenge>
      </gleis>
      <gleis id="Abzweig">
         <name>4</name>
         <laenge>600</laenge>
      </gleis>
	</hgleise>
	<ngleise>
      <gleis id="Schutzgleis">
         <name>5</name>
         <laenge>150</laenge>
      </gleis>
	</ngleise>
   </gleise>
   <gv>
        <ladestelle id="lade1" gleis="IBahn">
            <name>Feldrampe</name>
            <laenge einheit="achsen">4</laenge>
        </ladestelle>
        <verlader>
            <name>VEB Forstwirtschaft Karl-Marx-Stadt BT Oberkaselwitz</name>
            <empfang>
                <ladegut ladestelle="lade1">
                    <name>Holz</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </empfang>
            <versand>
                <ladegut ladestelle="lade1">
                    <name>Holz</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </versand>
        </verlader>
        <verlader>
            <name>LPG Oberkaselwitz</name>
            <empfang>
                <ladegut ladestelle="lade1">
                    <name>Zuckerrüben</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </empfang>
            <versand>
                <ladegut ladestelle="lade1">
                    <name>Zuckerrüben</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </versand>
        </verlader>
        <verlader>
            <name>DR Fahrleitungsbau Lagerplatz Oberkaselwitz</name>
            <empfang>
                <ladegut ladestelle="lade1">
                    <name>Teile für Fahrleitungsbau</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
                <ladegut ladestelle="lade1">
                    <name>Schwellen</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </empfang>
            <versand>
                <ladegut ladestelle="lade1">
                    <name>Teile für Fahrleitungsbau</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
                <ladegut ladestelle="lade1">
                    <name>Schwellen</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </versand>
        </verlader>
        <verlader>
            <name>NVA 9.Panzerbattalion</name>
            <empfang>
                <ladegut ladestelle="lade1">
                    <name>Munitionscontainer</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
                <ladegut ladestelle="lade1">
                    <name>Panzer</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </empfang>
            <versand>
                <ladegut ladestelle="lade1">
                    <name>Munitionscontainer</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
                <ladegut ladestelle="lade1">
                    <name>Panzer</name>
                    <gattung>Res, Rgs</gattung>
                    <wagen zeitraum="tag"></wagen>
                </ladegut>
            </versand>
        </verlader>
        <bemerkung>Bedienung der Feldrampe nur per Sperrfahrt in Abstimmung mit FDL OKW und Anschluß I-Bahn[br]Entladung nur per Kran, keine Seitenrampe!</bemerkung>
   </gv>
   <bemerkung>2gleisige Hauptbahn Abzweig auf 1gleisige Hauptbahn und Abzweig auf IBahn</bemerkung>
</bahnhof>

=== fktt-module/datasheets/bie.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Biegen</name>
	<kuerzel>BIE</kuerzel>
	<typ>Sbf</typ>
	<verwaltung>DB</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>DiThe100</modulnr>
	<plan src="bie.jpg"/>
	<gleise>
		<zulaufstrecken>
			<links nr="1">1gl</links>
		</zulaufstrecken>
		<hgleise>
			<gleis id="gl1">
				<name>1</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl2">
				<name>2</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl3">
				<name>3</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl4">
				<name>4</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl5">
				<name>5</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl6">
				<name>6</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl7">
				<name>7</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl8">
				<name>8</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl9">
				<name>9</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl10">
				<name>10</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl11">
				<name>11</name>
				<laenge>1700</laenge>
			</gleis>
			<gleis id="gl12">
				<name>12</name>
				<laenge>1700</laenge>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis id="l1">
				<name>l1</name>
				<laenge>150</laenge>
				<bemerkung>Lok Abstell</bemerkung>
			</gleis>
			<gleis id="l2">
				<name>l2</name>
				<laenge>150</laenge>
				<bemerkung>Lok Abstell</bemerkung>
			</gleis>
		</ngleise>
	</gleise>
	<bemerkung>Schwenkweiche</bemerkung>
</bahnhof>

=== fktt-module/datasheets/sum.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./bahnhof.xsl" type="text/xsl"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<bahnhof>
  <name>Stückgutumschlag</name>
  <kuerzel>SUM</kuerzel>
  <typ>Anst</typ>
  <verwaltung>DR</verwaltung>
  <maszstab>120</maszstab>
  <modulnr>EmOtt396</modulnr>
  <plan src="sum.jpg" />
  <gleise>
    <zulaufstrecken>
      <links nr="1">IBahn</links>
      <rechts nr="1">IBahn</rechts>
    </zulaufstrecken>
    <hgleise>
      <gleis id="gleis_I-Bahn-Stammgleis">
        <name>I-Bahn-Stammgleis</name>
        <laenge>1800</laenge>
      </gleis>
    </hgleise>
    <ngleise>
      <gleis id="gleis_11">
        <name>11</name>
        <laenge>1000</laenge>
        <bemerkung>Umladung Feuergut</bemerkung>
      </gleis>
      <gleis id="gleis_1">
        <name>1</name>
        <laenge>1500</laenge>
        <bemerkung>Umladung Stückgut</bemerkung>
      </gleis>
      <gleis id="gleis_2">
        <name>2</name>
        <laenge>1500</laenge>
        <bemerkung>Umladung Stückgut</bemerkung>
      </gleis>
      <gleis id="gleis_3">
        <name>3</name>
        <laenge>2000</laenge>
        <bemerkung>Umladung Stückgut</bemerkung>
      </gleis>
      <gleis id="gleis_4">
        <name>4</name>
        <laenge>2000</laenge>
        <bemerkung>Abstellung Wagen</bemerkung>
      </gleis>
      <gleis id="gleis_31">
        <name>31</name>
        <laenge>1800</laenge>
        <bemerkung>Abstellung Wagen / Umfahrung</bemerkung>
      </gleis>
    </ngleise>
  </gleise>
  <gv>
    <ladestelle id="Feuergutrampe" gleis="gleis_11">
      <name>Feuergutrampe</name>
      <laenge>1000</laenge>
    </ladestelle>
    <ladestelle id="St_ckgutrampe_A" gleis="gleis_1">
      <name>Stückgutrampe A</name>
      <laenge>1400</laenge>
    </ladestelle>
    <ladestelle id="St_ckgutrampe_B" gleis="gleis_2">
      <name>Stückgutrampe B</name>
      <laenge>1500</laenge>
    </ladestelle>
    <ladestelle id="St_ckgutrampe_C" gleis="gleis_3">
      <name>Stückgutrampe C</name>
      <laenge>1600</laenge>
    </ladestelle>
    <verlader>
      <name>Stückgutumschlag</name>
    </verlader>
  </gv>
</bahnhof>
