=== fktt-module/datasheets/bahnhof.dtd
<!ELEMENT bahnhof (name,kuerzel,typ,verwaltung,maszstab,modulnr,plan?,gleise,pv?,gv?,bemerkung?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT kuerzel (#PCDATA)>
<!ELEMENT typ (#PCDATA)>
<!ELEMENT verwaltung (#PCDATA)>
<!ELEMENT maszstab (#PCDATA)>
<!ELEMENT modulnr (#PCDATA)>
<!ELEMENT plan EMPTY>
	<!ATTLIST plan src CDATA #REQUIRED>
<!ELEMENT gleise (zulaufstrecken+,hgleise+,ngleise?)>
<!ELEMENT zulaufstrecken (links*,rechts*)>
<!ELEMENT links (#PCDATA)>
	<!ATTLIST links nr CDATA #REQUIRED>
<!ELEMENT rechts (#PCDATA)>
	<!ATTLIST rechts nr CDATA #REQUIRED>
<!ELEMENT hgleise (gleis+)>
<!ELEMENT ngleise (gleis+)>
<!ELEMENT gleis (name,laenge,bemerkung?)>
	<!ATTLIST gleis id ID #IMPLIED>
<!ELEMENT laenge (#PCDATA)>
	<!ATTLIST laenge einheit (mm|cm|achsen) "mm">
<!ELEMENT pv (bahnsteig+,bemerkung?)>
<!ELEMENT bahnsteig (name?,laenge)>
	<!ATTLIST bahnsteig gleis IDREFS #REQUIRED>
<!ELEMENT bemerkung (#PCDATA)>
<!ELEMENT gv (ladestelle+,verlader+,bemerkung?)>
<!ELEMENT ladestelle (name,laenge)>
	<!ATTLIST ladestelle id ID #IMPLIED>
	<!ATTLIST ladestelle gleis IDREFS #REQUIRED>
<!ELEMENT verlader (name,empfang?,versand?)>
<!ELEMENT empfang (ladegut+)>
<!ELEMENT ladegut (name,gattung,wagen)>
	<!ATTLIST ladegut ladestelle IDREFS #REQUIRED>
	<!ATTLIST ladegut typ (normal|stueckgut|expressgut) "normal">
<!ELEMENT gattung (#PCDATA)>
<!ELEMENT wagen (#PCDATA)>
	<!ATTLIST wagen zeitraum (tag|woche) "woche">
<!ELEMENT versand (ladegut+)>

=== fktt-module/datasheets/art-VI.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
    <name>Altranft</name>
    <kuerzel>ART</kuerzel>
    <typ>Bf</typ>
    <verwaltung/>
    <maszstab>120</maszstab>
    <modulnr>AdRan204</modulnr>

	<plan src="art.png" />
    <gleise>
        <zulaufstrecken>
           <links nr="1">1gl</links>
           <rechts nr="1">1gl</rechts>
        </zulaufstrecken>
        <hgleise>
           <gleis id="bahnsteig">

               <name>1</name>
               <laenge einheit="cm">110</laenge>
			   <bemerkung>Durchgehendes Hauptgleis</bemerkung>
           </gleis>
        </hgleise>
        <ngleise>
           <gleis id="ladestrg">

               <name>2</name>
               <laenge einheit="cm">90</laenge>
           </gleis>
           <gleis id="laderampeg">
               <name>2a</name>
               <laenge einheit="cm">30</laenge>
           </gleis>

        </ngleise>
    </gleise>
    <pv>
        <bahnsteig gleis="bahnsteig">
            <name>1</name>
            <laenge einheit="cm">110</laenge>
        </bahnsteig>
    </pv>

	<gv>
		<ladestelle id="ladestr" gleis="ladestrg">
			<name>Ladestraße</name>
			<laenge einheit="cm">45</laenge>
		</ladestelle>
		<ladestelle id="laderampe" gleis="laderampeg">
			<name>Laderampe</name>

			<laenge einheit="cm">25</laenge>
		</ladestelle>
        <verlader>
            <name>Landesforstverwaltung Brandenburg / Forstwirtschaft Barnim</name>
            <versand>
                <ladegut ladestelle="ladestr">
                    <name>Baumstämme</name>
                    <gattung>E, L</gattung>
                    <wagen zeitraum="tag">0.25</wagen>
                </ladegut>
            </versand>
	</verlader>
	</gv>
</bahnhof>

=== fktt-module/datasheets/bas.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Basdorf</name>
	<kuerzel>BAS</kuerzel>
	<typ>Bf</typ>
	<verwaltung>DR</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>FrNev210</modulnr>
	<plan src="bas.png" />
	<gleise>
		<zulaufstrecken>
			<links nr="1">1gl</links>
			<rechts nr="1">1gl</rechts>
			<rechts nr="2">1gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis id="hg1">
				<name>1</name>
				<laenge einheit="cm">268</laenge>
			</gleis>
			<gleis id="hg2">
				<name>2</name>
				<laenge einheit="cm">130</laenge>
			</gleis>
			<gleis>
				<name>3</name>
				<laenge einheit="cm">268</laenge>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis>
				<name>4</name>
				<laenge einheit="cm">136</laenge>
			</gleis>
			<gleis>
				<name>5</name>
				<laenge einheit="cm">140</laenge>
			</gleis>
			<gleis>
				<name>6</name>
				<laenge einheit="cm">140</laenge>
			</gleis>
			<gleis id="bmgleis">
				<name>7</name>
				<laenge einheit="cm">45</laenge>
			</gleis>
			<gleis>
				<name>7a</name>
				<laenge einheit="cm">18</laenge>
			</gleis>
			<gleis>
				<name>8</name>
				<laenge einheit="cm">90</laenge>
				<bemerkung>Ziehgleis</bemerkung>
			</gleis>
			<gleis id="ladestrgleis">
				<name>9</name>
				<laenge einheit="cm">130</laenge>
			</gleis>
			<gleis>
				<name>10</name>
				<laenge einheit="cm">30</laenge>
			</gleis>
			<gleis>
				<name>12</name>
				<laenge einheit="cm">35</laenge>
				<bemerkung>Bekohlung</bemerkung>
			</gleis>
			<gleis>
				<name>13</name>
				<laenge einheit="cm">30</laenge>
			</gleis>
			<gleis>
				<name>14</name>
				<laenge einheit="cm">30</laenge>
			</gleis>
		</ngleise>
	</gleise>
	<pv>
		<bahnsteig gleis="hg1">
			<name>1</name>
			<laenge einheit="cm">120</laenge>
		</bahnsteig>
		<bahnsteig gleis="hg2">
			<name>2</name>
			<laenge einheit="cm">120</laenge>
		</bahnsteig>
	</pv>
	<gv>
		<ladestelle id="ladestr" gleis="ladestrgleis">
			<name>Ladestraße</name>
			<laenge einheit="cm">130</laenge>
		</ladestelle>
		<ladestelle id="bm" gleis="bmgleis">
			<name>Bm-Gleis</name>
			<laenge einheit="cm">45</laenge>
		</ladestelle>
		<verlader>
			<name>Bahnmeisterei</name>
			<empfang>
				<ladegut ladestelle="bm">
					<name>Schotter</name>
					<gattung>F, E</gattung>
					<wagen>1</wagen>
				</ladegut>
				<ladegut ladestelle="bm">
					<name>Schienen</name>
					<gattung>R</gattung>
					<wagen>1</wagen>
				</ladegut>
				<ladegut ladestelle="bm">
					<name>Kleineisen</name>
					<gattung>E</gattung>
					<wagen>1</wagen>
				</ladegut>
			</empfang>
		</verlader>
		<verlader>
			<name>VEB Kohlehandel "Rekord"</name>
			<empfang>
				<ladegut ladestelle="ladestr">
					<name>Kohle</name>
					<gattung>E, F</gattung>
					<wagen>14</wagen>
				</ladegut>
			</empfang>
		</verlader>
		<verlader>
			<name>BHG Baustoffversorgung</name>
			<empfang>
				<ladegut ladestelle="ladestr">
					<name>Steine</name>
					<gattung>E</gattung>
					<wagen>3</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Kies</name>
					<gattung>E, F</gattung>
					<wagen>3</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Zement</name>
					<gattung>U</gattung>
					<wagen>3</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Fließen</name>
					<gattung>G</gattung>
					<wagen>1</wagen>
				</ladegut>
			</empfang>
		</verlader>
		<verlader>
			<name>DVP (Bereitschaftspolizei)</name>
			<empfang>
				<ladegut ladestelle="ladestr">
					<name>Kohle</name>
					<gattung>E</gattung>
					<wagen>2</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>W50</name>
					<gattung>R, S, K</gattung>
					<wagen>1</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Diesel</name>
					<gattung>Z</gattung>
					<wagen>1</wagen>
				</ladegut>
			</empfang>
		</verlader>
		<verlader>
			<name>GPG Frischgemüse Basdorf</name>
			<empfang>
				<ladegut ladestelle="ladestr">
					<name>Gemüsestiegen</name>
					<gattung>G</gattung>
					<wagen>5</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Gitterboxen</name>
					<gattung>G</gattung>
					<wagen>3</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="ladestr">
					<name>Frischgemüse</name>
					<gattung>I</gattung>
					<wagen>5</wagen>
				</ladegut>
				<ladegut ladestelle="ladestr">
					<name>Kartoffeln</name>
					<gattung>G</gattung>
					<wagen>3</wagen>
				</ladegut>
			</versand>
		</verlader>
	</gv>
	<bemerkung></bemerkung>
</bahnhof>

=== fktt-module/datasheets/afp.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
  <name>Filzpantoffelfabrik</name>
  <kuerzel>AFP</kuerzel>
  <typ>Anst</typ>
  <verwaltung>DR</verwaltung>
  <maszstab>120</maszstab>
  <modulnr>MaRue394</modulnr>
  <plan src="afp.svg" />
  <gleise>
    <zulaufstrecken>
      <links nr="1">1gl</links>
      <rechts nr="1">1gl</rechts>
    </zulaufstrecken>
    <hgleise>
      <gleis id="hg1">
        <name>durchgehendes Streckengleis</name>
        <laenge>1395</laenge>
      </gleis>
    </hgleise>
    <ngleise>
      <gleis id="ng1">
        <name>1</name>
        <laenge>455</laenge>
      </gleis>
      <gleis id="ng2">
        <name>2</name>
        <laenge>190</laenge>
      </gleis>
    </ngleise>
  </gleise>
  <gv>
    <ladestelle id="ladestrasse" gleis="ng1">
      <name>Ladestraße</name>
      <laenge>160</laenge>
    </ladestelle>
    <ladestelle id="rampe" gleis="ng1">
      <name>Rampe</name>
      <laenge>185</laenge>
    </ladestelle>
    <ladestelle id="heizhaus" gleis="ng2">
      <name>Heizhaus</name>
      <laenge>115</laenge>
    </ladestelle>
    <verlader>
      <name>VEB Filzpantoffel</name>
      <empfang>
        <ladegut ladestelle="rampe">
          <name>Filz als Rollenware, Klebstoffe, Stoff</name>
          <gattung>G, H</gattung>
          <wagen>2</wagen>
        </ladegut>
        <ladegut ladestelle="heizhaus">
          <name>Braunkohle, Koks</name>
          <gattung>E</gattung>
          <wagen>1</wagen>
        </ladegut>
      </empfang>
      <versand>
        <ladegut ladestelle="rampe">
          <name>Filzprodukte Hausschuhe, Stiefel, Hüte</name>
          <gattung>G, H</gattung>
          <wagen>2</wagen>
        </ladegut>
        <ladegut ladestelle="heizhaus">
          <name>Schlacke, Asche</name>
          <gattung>E, U</gattung>
          <wagen>0.5</wagen>
        </ladegut>
      </versand>
    </verlader>
    <bemerkung>Verlader und Ladegüter sind noch einzutragen.</bemerkung>
  </gv>
</bahnhof>

=== fktt-module/datasheets/rhs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
  <name>Abzw. Reichertshausen</name>
  <kuerzel>RHS</kuerzel>
  <typ>Bf</typ>
  <verwaltung>DB</verwaltung>
  <maszstab>120</maszstab>
  <modulnr>TTBay415</modulnr>
  <plan src="rhs.png" />
  <gleise>
    <zulaufstrecken>
      <links nr="1">2gl</links>
      <links nr="2">2gl</links>
      <links nr="3">1gl</links>
      <rechts nr="1">2gl</rechts>
      <rechts nr="2">2gl</rechts>
      <rechts nr="3">1gl</rechts>
    </zulaufstrecken>
    <hgleise>
      <gleis id="G1">
        <name>1</name>
        <laenge>1500</laenge>
        <bemerkung>Hauptgleis Hauptstrecke</bemerkung>
      </gleis>
      <gleis id="G2">
        <name>2</name>
        <laenge>1500</laenge>
        <bemerkung>Hauptgleis Hauptstrecke</bemerkung>
      </gleis>
      <gleis id="G3">
        <name>3</name>
        <laenge>1600</laenge>
        <bemerkung>Hauptgleis Nebenbahn</bemerkung>
      </gleis>
    </hgleise>
  </gleise>
</bahnhof>

=== fktt-module/datasheets/vie.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Vieselbach</name>
	<kuerzel>VIE</kuerzel>
	<typ>Bf</typ>
	<verwaltung>DR</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>StErf260</modulnr>
	<plan src="vie.png"/>
	<gleise>
		<zulaufstrecken>
			<links nr="1">2gl</links>
			<rechts nr="1">2gl</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis id="Ueberholungsgleis">
				<name>1</name>
				<laenge>3500</laenge>
				<bemerkung>Ueberholungsgleis in beide Fahrtrichtungen</bemerkung>
			</gleis>
			<gleis id="Durchgangsgleis_2">
				<name>2</name>
				<laenge>5000</laenge>
				<bemerkung>Durchgangsgleis im Richtungsverkehr</bemerkung>
			</gleis>
			<gleis id="Durchgangsgleis_3">
				<name>3</name>
				<laenge>5000</laenge>
				<bemerkung>Durchgangsgleis im Richtungsverkehr</bemerkung>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis id="Abstellgleis">
				<name>5</name>
				<laenge>950</laenge>
				<bemerkung>Abstellgleis</bemerkung>
			</gleis>
			<gleis id="Ladestrasseg">
				<name>6</name>
				<laenge>2100</laenge>
				<bemerkung>Rangiergleis, Ladestraße</bemerkung>
			</gleis>
			<gleis id="Gueterschuppeng">
				<name>7</name>
				<laenge>950</laenge>
				<bemerkung>Rangiergleis, Güterschuppen</bemerkung>
			</gleis>
			<gleis id="Kopframpeg">
				<name>8</name>
				<laenge>200</laenge>
				<bemerkung>Kopframpe</bemerkung>
			</gleis>
			<gleis id="A1a">
				<name>A1a</name>
				<laenge>1300</laenge>
				<bemerkung>Anschluß ACZ, Ladestraße</bemerkung>
			</gleis>
			<gleis id="A1b">
				<name>A1b</name>
				<laenge>700</laenge>
				<bemerkung>Anschluß ACZ, Ladestraße</bemerkung>
			</gleis>
			<gleis id="A2a">
				<name>A2a</name>
				<laenge>1100</laenge>
				<bemerkung>Umfahrgleis ACZ</bemerkung>
			</gleis>
			<gleis id="A2b">
				<name>A2b</name>
				<laenge>1200</laenge>
				<bemerkung>Anschluß ZOE, hier kann ein Normübergang Joschidul angebracht werden</bemerkung>
			</gleis>
		</ngleise>
	</gleise>
	<pv>
		<bahnsteig gleis="Ueberholungsgleis">
			<name>1</name>
			<laenge>1500</laenge>
		</bahnsteig>
		<bahnsteig gleis="Durchgangsgleis_2">
			<name>2</name>
			<laenge>1500</laenge>
		</bahnsteig>
		<bahnsteig gleis="Durchgangsgleis_3">
			<name>3</name>
			<laenge>1500</laenge>
		</bahnsteig>
		<bemerkung>Halt lediglich für Regionalverkehr</bemerkung>
	</pv>
	<gv>
		<ladestelle id="Ladestrasse" gleis="Ladestrasseg">
			<name>Ladestrasse</name>
			<laenge>750</laenge>
		</ladestelle>
		<ladestelle id="ACZ" gleis="A1a">
			<name>ACZ</name>
			<laenge>2000</laenge>
		</ladestelle>
		<ladestelle id="Kopframpe" gleis="Kopframpeg">
			<name>Kopframpe</name>
			<laenge>200</laenge>
		</ladestelle>
		<ladestelle id="Gueterschuppen" gleis="Gueterschuppeng">
			<name>Gueterschuppen</name>
			<laenge>350</laenge>
		</ladestelle>
		<verlader>
			<name>ACZ Vieselbach</name>
			<empfang>
				<ladegut ladestelle="ACZ">
					<name>Dünger</name>
					<gattung>G, T, E</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
				<ladegut ladestelle="ACZ">
					<name>Pestizide</name>
					<gattung>Z</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
			</empfang>
		</verlader>
		<verlader>
			<name>LPG (P) Vieselbach</name>
			<empfang>
				<ladegut ladestelle="Kopframpe">
					<name>Landmaschinen</name>
					<gattung>K, R, S</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Ladestrasse">
					<name>Futterrüben</name>
					<gattung>E</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Roggen</name>
					<gattung>T, G</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>Bahnmeisterei</name>
			<empfang>
				<ladegut ladestelle="Ladestrasse">
					<name>Gleisschotter</name>
					<gattung>F, E, K</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Schienen</name>
					<gattung>R, S</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Holzschwellen</name>
					<gattung>R, S, K</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Baustellenrückstände</name>
					<gattung>E, K, R</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
		</verlader>
		<verlader>
			<name>LPG (T) Hochstedt</name>
			<empfang>
				<ladegut ladestelle="Gueterschuppen">
					<name>Impfstoffe</name>
					<gattung>G</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Aufzuchtfutter</name>
					<gattung>G</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Ladestrasse">
					<name>Mastrinder</name>
					<gattung>G</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Schweine</name>
					<gattung>G</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>Getreidemühle Vieselbach</name>
			<empfang>
				<ladegut ladestelle="Ladestrasse">
					<name>Weizen</name>
					<gattung>G, T</gattung>
					<wagen zeitraum="woche">3</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Ladestrasse">
					<name>Weizenmehl</name>
					<gattung>G, T</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>Weizenschrot</name>
					<gattung>G, T</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>Brauerei Vieselbach</name>
			<empfang>
				<ladegut ladestelle="Ladestrasse">
					<name>Leergut</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
				<ladegut ladestelle="Gueterschuppen">
					<name>Flaschenverschlüsse</name>
					<gattung>G</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Gueterschuppen">
					<name>Reinigungsmittel</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Gueterschuppen">
					<name>Reinigungsmittel</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Ladestrasse">
					<name>Getränke</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>Möbelwek Wüstemann</name>
			<empfang>
				<ladegut ladestelle="Kopframpe">
					<name>Möbelspanplatten</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
				<ladegut ladestelle="Gueterschuppen">
					<name>Beschläge</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="Ladestrasse">
					<name>Möbel</name>
					<gattung>G, H</gattung>
					<wagen zeitraum="woche">2</wagen>
				</ladegut>
			</versand>
		</verlader>
		<verlader>
			<name>Kohlehandel Vieselbach</name>
			<empfang>
				<ladegut ladestelle="Ladestrasse">
					<name>Braunkohlenbrikett</name>
					<gattung>E, F</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
				<ladegut ladestelle="Ladestrasse">
					<name>BHT-Koks</name>
					<gattung>E</gattung>
					<wagen zeitraum="woche">1</wagen>
				</ladegut>
			</empfang>
		</verlader>
	</gv>
	<bemerkung>Vorbahnhof zu großem Bahnhof</bemerkung>
</bahnhof>

=== fktt-module/datasheets/bls-V.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./bahnhof.xsl" type="text/xsl"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd">

<bahnhof>
  <name>BHG Lilienstra√üe</name>
  <kuerzel>BLS</kuerzel>
  <typ>Bf</typ>
  <verwaltung>DR</verwaltung>
  <maszstab>120.0</maszstab>
  <modulnr>JaDan363</modulnr>
  <plan src="bls.png" />
  <gleise>
    <zulaufstrecken>
      <links nr="1">1gl</links>
      <rechts nr="1">1gl</rechts>
    </zulaufstrecken>
    <hgleise>
      <gleis id="gleis_Hauptgleis">
        <name>Hauptgleis</name>
        <laenge einheit="cm">90.0</laenge>
      </gleis>
    </hgleise>
    <ngleise>
      <gleis id="gleis_BHG">
        <name>BHG</name>
        <laenge einheit="cm">40.0</laenge>
        <bemerkung>Anschlussgleis mit Gleissperre</bemerkung>
      </gleis>
    </ngleise>
  </gleise>
</bahnhof>

=== fktt-module/datasheets/blw.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bahnhof SYSTEM "./bahnhof.dtd" >
<?xml-stylesheet type="text/xsl" href="./bahnhof.xsl" ?>
<bahnhof>
	<name>Blütenweiß</name>
	<kuerzel>BLW</kuerzel>
	<typ>Anst</typ>
	<verwaltung>DR</verwaltung>
	<maszstab>120</maszstab>
	<modulnr>ReBuc359</modulnr>
    <plan src="blw.jpg"/>
	<gleise>
		<zulaufstrecken>
			<links nr="1">I-Bahn</links>
			<rechts nr="1">I-Bahn</rechts>
		</zulaufstrecken>
		<hgleise>
			<gleis>
				<name>Strecke</name>
				<laenge></laenge>
			</gleis>
		</hgleise>
		<ngleise>
			<gleis id="gleis1">
				<name>Wäscherei</name>
				<laenge>500</laenge>
			</gleis>
			<gleis id="gleis2">
				<name>Post</name>
				<laenge>300</laenge>
			</gleis>
		</ngleise>
	</gleise>
	<gv>
		<ladestelle id="ladestelle1" gleis="gleis1">
			<name>Kesselhaus</name>
			<laenge einheit="cm">15</laenge>
		</ladestelle>
		<ladestelle id="ladestelle3" gleis="gleis1">
			<name>Abfüllstelle</name>
			<laenge einheit="cm">10</laenge>
		</ladestelle>
		<ladestelle id="ladestelle2" gleis="gleis2">
			<name>Ladegleis</name>
			<laenge einheit="cm">30</laenge>
		</ladestelle>
		<verlader>
			<name>VEB Blütenweiß Wäschereibetrieb</name>
			<empfang>
				<ladegut ladestelle="ladestelle1">
					<name>Kohle</name>
					<gattung>E</gattung>
					<wagen zeitraum="tag">2</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="ladestelle3">
					<name>Lauge</name>
					<gattung>Z</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
			</versand>
		</verlader>
        <verlader>
            <name>Deutsche Post Bauhof</name>
			<empfang>
				<ladegut ladestelle="ladestelle2">
					<name>Kabel</name>
					<gattung>E, K</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
				<ladegut ladestelle="ladestelle2">
					<name>Leitungsstangen</name>
					<gattung>K</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
			</empfang>
			<versand>
				<ladegut ladestelle="ladestelle2">
					<name>leere Kabeltrommeln</name>
					<gattung>E, K</gattung>
					<wagen zeitraum="tag">1</wagen>
				</ladegut>
			</versand>
        </verlader>
	</gv>
</bahnhof>
